server:
  port: 85
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?userSSL=false
    username: root
    password: byk20040728
  application:
    name: BaseLogin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

