spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: MailLogin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  mail:
    host: smtp.qq.com
    username: 1619728906@qq.com
    password: occiinoivuhadceg

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false
    username: root
    password: byk20040728
server:
  port: 83

