server:
  port: 81
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
    username: root
    password: byk20040728
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080